### PR TITLE
Aws elasticsearch plugin and Jenkins automation

### PR DESCRIPTION
**Pull request by kuzaxak**
See additional info in commits messages

### CODE REVIEW

**Comment by kuzaxak** [comment]
!build

**Comment by sm-deployer** [comment]
Built and published `1.4.2-800b60e`

**Review by take-five — APPROVED** [review]

**Comment by take-five** [comment]
Current stable version is 1.12, version 1.4 was released 2 years age. Changelog contains a gazillion of bug fixes and improvements.
When are we going to upgrade? Maybe now is the time to upgrade?

**Comment by mpi1** [comment]
@kneepdee Did you test our configuration with this as well?

**Comment by kuzaxak** [comment]
Yes, I deployed it to acceptance. Everything looks fine. Will double check today.

**Pull request merged**
