### PR TITLE
Update Ruby gems (non-major)

### PR DESCRIPTION
**Pull request by sm-deployer**
This PR contains the following updates:

| Package | Update | Change |
|---|---|---|
| fluent-logger | minor | `0.8.0` -> `0.9.0` |
| fluent-plugin-kafka | minor | `0.9.2` -> `0.17.4` |
| fluent-plugin-kubernetes_metadata_filter | minor | `2.5.2` -> `2.9.4` |
| fluent-plugin-prometheus | minor | `1.3.0` -> `1.8.5` |
| fluent-plugin-record-modifier | minor | `2.0.1` -> `2.1.0` |
| fluent-plugin-rewrite-tag-filter | minor | `2.1.1` -> `2.4.0` |
| fluent-plugin-s3 | minor | `1.1.9` -> `1.6.1` |
| fluent-plugin-systemd | patch | `1.0.4` -> `1.0.5` |
| fluent-plugin-td | minor | `1.0.0` -> `1.1.0` |
| fluent-plugin-webhdfs | minor | `1.2.3` -> `1.5.0` |
| fluentd | minor | `1.4.2` -> `1.14.4` |

---

### Configuration

📅 **Schedule**: At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get [config help](https://togithub.com/renovatebot/renovate/discussions) if that's undesired.

---

 - [ ] If you want to rebase/retry this PR, click this checkbox.

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

### CODE REVIEW

**Review by kuzaxak — COMMENTED** [review]
Need to check migration from 1.4 to 1.12 for fluentd

**Comment by sm-deployer** [comment]
### ⚠️ Artifact update problem

Renovate failed to update an artifact related to this branch. You probably do not want to merge this PR as-is.

♻️ Renovate will retry this branch, including artifacts, only when one of the following happens:

 - any of the package files in this branch needs updating, or 
 - the branch becomes conflicted, or
 - you check the rebase/retry checkbox if found above, or
 - you rename this PR's title to start with "rebase!" to trigger it manually

The artifact failure details are included below:

##### File name: Gemfile.lock

```
Fetching gem metadata from http://rubygems.org/............
Resolving dependencies....

[DEPRECATED] The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://rubygems.org' if not.
Bundler could not find compatible versions for gem "fluentd":
  In Gemfile:
    fluentd (= 1.13.0)

fluent-plugin-kubernetes_metadata_filter (= 2.7.0) was resolved to 2.7.0,
which depends on
      fluentd (< 1.13, >= 0.14.0)

```

**Comment by sm-deployer** [comment]
### ⚠ Artifact update problem

Renovate failed to update an artifact related to this branch. You probably do not want to merge this PR as-is.

♻ Renovate will retry this branch, including artifacts, only when one of the following happens:

 - any of the package files in this branch needs updating, or 
 - the branch becomes conflicted, or
 - you check the rebase/retry checkbox if found above, or
 - you rename this PR's title to start with "rebase!" to trigger it manually

The artifact failure details are included below:

##### File name: Gemfile.lock

```
Fetching gem metadata from http://rubygems.org/............
Resolving dependencies....

[DEPRECATED] The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://rubygems.org' if not.
Bundler could not find compatible versions for gem "prometheus-client":
  In snapshot (Gemfile.lock):
    prometheus-client (>= 2.1.0)

  In Gemfile:
    fluent-plugin-prometheus (= 1.8.5) was resolved to 1.8.5, which depends on
      prometheus-client (< 0.10)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

```

**Comment by r2bit** [comment]
Oh my god their Docker images are a mess.

**Comment by r2bit** [comment]
!build

**Comment by sm-deployer** [comment]
Built and published `1.14.4-7bca797`

**Review by r2bit — APPROVED** [review]

**Pull request merged**
